### ISSUE TITLE
[Issue]: Fresh install fails with NumPy 2.1.2 + onnxruntime 1.17.1 ABI error; upgrading onnxruntime to 1.27.0 fixes startup

### ISSUE THREAD

**Issue by Panki1212** [vladmandic/sdnext#4949]
### Issue Description

Fresh SD.Next install on Windows 11 / Python 3.12 / NVIDIA CUDA 13 stack fails during startup when importing onnxruntime.

Installed packages shown by SD.Next:
- numpy==2.1.2
- onnxruntime==1.17.1
- torch initially torch==2.12.1+cpu, torchvision==0.27.0+cu130, then SD.Next attempts to switch to NVIDIA torch
- diffusers==0.39.0.dev0
- transformers==5.12.1
- accelerate==1.14.0

Startup error:
A module that was compiled using NumPy 1.x cannot be run in NumPy 2.1.2 as it may crash.

Trace points to:
venv\Lib\site-packages\onnxruntime\capi\onnxruntime_pybind11_state

Workaround:
venv\Scripts\python.exe -m pip uninstall -y onnxruntime onnxruntime-gpu
venv\Scripts\python.exe -m pip install -U onnxruntime

This installed onnxruntime==1.27.0 and SD.Next started successfully.

### Version Platform Description

[sdnext.log.1.txt](https://github.com/user-attachments/files/29172202/sdnext.log.1.txt)

### Relevant log output

```shell
"08:24:50-307210 DEBUG Initializing: libraries A module that was compiled using NumPy 1.x cannot be run in NumPy 2.1.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'. If you are a user of the module, the easiest solution will be to downgrade to 'numpy<2' or try to upgrade the affected module. We expect that some modules will need time to support NumPy 2. Traceback (most recent call last): File "G:\StabilityMatrix\Data\Packages\SD.Next\launch.py", line 355, in <module> main() File "G:\StabilityMatrix\Data\Packages\SD.Next\launch.py", line 316, in main uv, instance = start_server(immediate=True, server=None) File "G:\StabilityMatrix\Data\Packages\SD.Next\launch.py", line 214, in start_server module_spec.loader.exec_module(server) File "G:\StabilityMatrix\Data\Packages\SD.Next\webui.py", line 15, in <module> import modules.loader File "G:\StabilityMatrix\Data\Packages\SD.Next\modules\loader.py", line 178, in <module> import onnxruntime # pylint: disable=W0611,C0411 File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module> from onnxruntime.capi._pybind_state import ExecutionMode # noqa: F401 File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module> from .onnxruntime_pybind11_state import * # noqa G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\numpy\core\_multiarray_umath.py:44 in __getattr__ 43 sys.stderr.write(msg + tb_msg) ❱ 44 raise ImportError(msg) 45 ImportError: A module that was compiled using NumPy 1.x cannot be run in NumPy 2.1.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'. If you are a user of the module, the easiest solution will be to downgrade to 'numpy<2' or try to upgrade the affected module. We expect that some modules will need time to support NumPy 2. 08:25:08-872037 WARNING Torch onnxruntime: 08:25:11-496867 INFO Torch: torch==2.12.1+cpu torchvision==0.27.0+cu130 08:25:11-497866 INFO Packages: diffusers==0.39.0.dev0 transformers==5.12.1 accelerate==1.14.0 gradio==3.43.2 pydantic==2.13.4 numpy==2.1.2 cv2==4.13.0 08:25:11-510370 DEBUG Initializing: shared module 08:25:11-606079 DEBUG Initializing: pipelines A module that was compiled using NumPy 1.x cannot be run in NumPy 2.1.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'. If you are a user of the module, the easiest solution will be to downgrade to 'numpy<2' or try to upgrade the affected module. We expect that some modules will need time to support NumPy 2. Traceback (most recent call last): File "G:\StabilityMatrix\Data\Packages\SD.Next\launch.py", line 355, in <module> main() File "G:\StabilityMatrix\Data\Packages\SD.Next\launch.py", line 316, in main uv, instance = start_server(immediate=True, server=None) File "G:\StabilityMatrix\Data\Packages\SD.Next\launch.py", line 214, in start_server module_spec.loader.exec_module(server) File "G:\StabilityMatrix\Data\Packages\SD.Next\webui.py", line 20, in <module> from modules import shared File "G:\StabilityMatrix\Data\Packages\SD.Next\modules\shared.py", line 24, in <module> from modules import shared_items # pylint: disable=unused-import File "G:\StabilityMatrix\Data\Packages\SD.Next\modules\shared_items.py", line 42, in <module> 'HunyuanImage': getattr(diffusers, 'HunyuanImagePipeline', None), File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\diffusers\utils\import_utils.py", line 1043, in __getattr__ value = getattr(module, name) File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\diffusers\utils\import_utils.py", line 1043, in __getattr__ value = getattr(module, name) File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\diffusers\utils\import_utils.py", line 1042, in __getattr__ module = self._get_module(self._class_to_module[name]) File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\diffusers\utils\import_utils.py", line 1052, in _get_module return importlib.import_module("." + module_name, self.__name__) File "G:\Python312\Lib\importlib\__init__.py", line 90, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\diffusers\pipelines\hunyuan_image\pipeline_hunyuanimage.py", line 25, in <module> from ...guiders import AdaptiveProjectedMixGuidance File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\diffusers\guiders\__init__.py", line 25, in <module> from .frequency_decoupled_guidance import FrequencyDecoupledGuidance File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\diffusers\guiders\frequency_decoupled_guidance.py", line 35, in <module> from kornia.geometry import pyrup as upsample_and_blur_func File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\__init__.py", line 32, in <module> from . import ( File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\__init__.py", line 24, in <module> from kornia.augmentation import auto, container File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\auto\__init__.py", line 23, in <module> from .autoaugment import AutoAugment File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\auto\autoaugment\__init__.py", line 23, in <module> from .autoaugment import AutoAugment File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\auto\autoaugment\autoaugment.py", line 24, in <module> from kornia.augmentation.auto.base import SUBPOLICY_CONFIG, PolicyAugmentBase File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\auto\base.py", line 23, in <module> from kornia.augmentation.auto.operations.base import OperationBase File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\auto\operations\__init__.py", line 25, in <module> from .policy import PolicySequential File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\auto\operations\policy.py", line 25, in <module> from kornia.augmentation.container.base import ImageSequentialBase, TransformMatrixMinIn File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\container\__init__.py", line 23, in <module> from kornia.augmentation.container.augment import AugmentationSequential File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\container\augment.py", line 24, in <module> from kornia.augmentation._2d.base import RigidAffineAugmentationBase2D File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\_2d\__init__.py", line 19, in <module> from kornia.augmentation._2d.intensity import * File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\_2d\intensity\__init__.py", line 47, in <module> from kornia.augmentation._2d.intensity.plasma import RandomPlasmaBrightness, RandomPlasmaContrast, RandomPlasmaShadow File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\augmentation\_2d\intensity\plasma.py", line 24, in <module> from kornia.contrib import diamond_square File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\contrib\__init__.py", line 39, in <module> from .image_stitching import ImageStitcher File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\contrib\image_stitching.py", line 24, in <module> from kornia.feature import LocalFeatureMatcher, LoFTR File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\feature\__init__.py", line 66, in <module> from .lightglue_onnx import OnnxLightGlue File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\feature\lightglue_onnx\__init__.py", line 23, in <module> from .lightglue import OnnxLightGlue File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\kornia\feature\lightglue_onnx\lightglue.py", line 31, in <module> import onnxruntime as ort File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module> from onnxruntime.capi._pybind_state import ExecutionMode # noqa: F401 File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module> from .onnxruntime_pybind11_state import * # noqa G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\numpy\core\_multiarray_umath.py:44 in __getattr__ 43 sys.stderr.write(msg + tb_msg) ❱ 44 raise ImportError(msg) 45 ImportError: A module that was compiled using NumPy 1.x cannot be run in NumPy 2.1.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'. If you are a user of the module, the easiest solution will be to downgrade to 'numpy<2' or try to upgrade the affected module. We expect that some modules will need time to support NumPy 2. 08:25:12-642763 DEBUG State initialized: id=1749772707760 08:25:12-644761 DEBUG Initializing: default modes 08:25:12-644761 DEBUG Initializing: settings A module that was compiled using NumPy 1.x cannot be run in NumPy 2.1.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'. If you are a user of the module, the easiest solution will be to downgrade to 'numpy<2' or try to upgrade the affected module. We expect that some modules will need time to support NumPy 2. Traceback (most recent call last): File "G:\StabilityMatrix\Data\Packages\SD.Next\launch.py", line 355, in <module> main() File "G:\StabilityMatrix\Data\Packages\SD.Next\launch.py", line 316, in main uv, instance = start_server(immediate=True, server=None) File "G:\StabilityMatrix\Data\Packages\SD.Next\launch.py", line 214, in start_server module_spec.loader.exec_module(server) File "G:\StabilityMatrix\Data\Packages\SD.Next\webui.py", line 20, in <module> from modules import shared File "G:\StabilityMatrix\Data\Packages\SD.Next\modules\shared.py", line 159, in <module> from modules import ui_definitions File "G:\StabilityMatrix\Data\Packages\SD.Next\modules\ui_definitions.py", line 9, in <module> from modules.onnx_impl import execution_providers File "G:\StabilityMatrix\Data\Packages\SD.Next\modules\onnx_impl\__init__.py", line 13, in <module> import onnxruntime as ort File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module> from onnxruntime.capi._pybind_state import ExecutionMode # noqa: F401 File "G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module> from .onnxruntime_pybind11_state import * # noqa G:\StabilityMatrix\Data\Packages\SD.Next\venv\Lib\site-packages\numpy\core\_multiarray_umath.py:44 in __getattr__ 43 sys.stderr.write(msg + tb_msg) ❱ 44 raise ImportError(msg) 45 ImportError: A module that was compiled using NumPy 1.x cannot be run in NumPy 2.1.2 as it may crash. To support both 1.x and 2.x versions of NumPy, modules must be compiled with NumPy 2.0. Some module may need to rebuild instead e.g. with 'pybind11>=2.12'. If you are a user of the module, the easiest solution will be to downgrade to 'numpy<2' or try to upgrade the affected module. We expect that some modules will need time to support NumPy 2. 08:25:12-667351 ERROR ONNX import error: G:\StabilityMatrix\Data\Packages\SD.Next\launch.py:355 in <module> 354 if __name__ == "__main__": ❱ 355 main() 356 G:\StabilityMatrix\Data\Packages\SD.Next\launch.py:316 in main 315 ❱ 316 uv, instance = start_server(immediate=True, server=None) 317 t_server = time.time() G:\StabilityMatrix\Data\Packages\SD.Next\launch.py:214 in start_server 213 log.debug(f'Starting module: {server}') ❱ 214 module_spec.loader.exec_module(server) 215 in exec_module:999 in _call_with_frames_removed:488 G:\StabilityMatrix\Data\Packages\SD.Next\webui.py:20 in <module> 19 import modules.migrate ❱ 20 from modules import shared 21 from modules.call_queue import queue_lock, wrap_queued_call, wrap_gradio_gpu_call # pylint: disable=unused-import G:\StabilityMatrix\Data\Packages\SD.Next\modules\shared.py:159 in <module> 158 log.debug('Initializing: settings') ❱ 159 from modules import ui_definitions 160 from modules.ui_definitions import OptionInfo, options_section # pylint: disable=unused-import G:\StabilityMatrix\Data\Packages\SD.Next\modules\ui_definitions.py:9 in <module> 8 from modules.dml import memory_providers, default_memory_provider ❱ 9 from modules.onnx_impl import execution_providers 10 from modules.memstats import memory_stats G:\StabilityMatrix\Data\Packages\SD.Next\modules\onnx_impl\__init__.py:19 in <module> 18 ❱ 19 class DynamicSessionOptions(ort.SessionOptions): 20 config: dict | None = None AttributeError: 'NoneType' object has no attribute 'SessionOptions' Press any key to continue . . ."
```

### Operating system

Windows

### Compute

nVidia CUDA

### Interface

ModernUI

### Branch

Master

### Model

Unspecified

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
workaround is valid.
you said that this is a completely fresh install? that's weird since sdnext does not force-install `onnxruntime==1.17.1`.
i just checked, and on fresh install it went for `onnxruntime==1.26.0` which works fine with `numpy==2.1.2`.
do you have any extensions on your system that may have downgraded it?

**Comment by Panki1212** [comment]
Thanks for checking.

To clarify the sequence more accurately:

I updated SD.Next from the previous commit to the latest one, and the onnxruntime / NumPy startup issue started after that update.

I did have ReActor Faceswap installed at the time, but ReActor was already not loading correctly during startup before this issue. It failed to import, although I unfortunately do not remember the exact ReActor error anymore.

After the SD.Next update started failing, I removed ReActor completely. Then, following troubleshooting advice, I deleted the old venv folder and let SD.Next create a completely fresh one. I started SD.Next directly using webui.bat with --reinstall.

Even with the newly recreated venv, the same startup error remained:

"AttributeError: 'NoneType' object has no attribute 'SessionOptions'" with the NumPy/onnxruntime mismatch.

So I cannot say for sure whether ReActor affected the environment earlier, but the important part is that the error persisted even after removing ReActor, deleting the old venv, recreating it, and running webui.bat --reinstall.

**Comment by vladmandic** [comment]
just checked reactor, yup, its forcing that exact old onnxruntime: <https://github.com/Gourieff/sd-webui-reactor-sfw/blob/0788c549ded1dc94346caf7da98aead7d4c27da8/install.py#L111>

now, why it survived uninstall and venv wipe, no clue, checking now.

**Comment by vladmandic** [comment]
i just pushed an update to dev branch:
- all onnxruntime execution paths are now non-critical, so even if there is a complete mismatch, it should still allow sdnext to function
- onnxruntime is version-checked on startup and upgraded as needed.
