### ISSUE TITLE
[Issue]: CK Flash Attention fails to compile on ROCm 6.4.1 (Recommended fork incompatible)

### ISSUE THREAD

**Issue by ShortTimeNoSee** [vladmandic/sdnext#4029]
### Issue Description

I'm trying to enable the CK Flash attention feature as recommended in the AMD ROCm.md documentation, but the installation is failing on a fresh ROCm 6.4.1 setup.

The build process for the recommended [Disty0/flash-attention@navi_rotary_fix](https://github.com/Disty0/flash-attention/tree/navi_rotary_fix) fork fails with a compilation error; I believe it's incompatible with the version of Composable Kernel included in ROCm 6.4.1. The Issues tab on that forked repository is disabled, so I am reporting it here as it is a documented feature.

Steps to reproduce:
* Set up an environment with the specifications above.
* In SD.Next, navigate to Settings > Compute Settings > SDP Options.
* Enable the CK Flash attention checkbox.
* Apply settings and restart the server.
* The server fails to install the flash_attn module on startup.
```
2:37:12-024646 ERROR    Install: pip: install --upgrade
                         git+https://github.com/Disty0/flash-attention@navi_rota
                         ry_fix
12:37:12-036809 ERROR    Torch attention: type="ck flash attention" No module
                         named 'flash_attn'
```
- Manually running the pip install command confirms the compilation error: `pip install git+https://github.com/Disty0/flash-attention@navi_rotary_fix`
```
error: no type named 'MaskingSpecialization' in namespace 'ck::tensor_operation::device'
```

Running with the `--reinstall` flag didn't work either.

### Version Platform Description

- GPU: Sapphire Pulse AMD Radeon RX 9070 (Navi 48 / gfx1201)
- Operating System: Ubuntu 24.04.2 LTS
- ROCm Version: 6.4.1 (rocm-hip-sdk is installed)
- Python Version: 3.10.18
- PyTorch Version: 2.9.0.dev20250705+rocm6.4
- ninja-build is installed
- Firefox 135.0

```
13:25:36-231899 INFO     Starting SD.Next                                       
13:25:36-233318 INFO     Logger: file="/home/nick/sdnext/sdnext.log" level=INFO 
                         host="Z890-EAGLE-WIFI7" size=2958248 mode=append       
13:25:36-233810 INFO     Python: version=3.10.18 platform=Linux                 
                         bin="/home/nick/sdnext/venv/bin/python3"               
                         venv="/home/nick/sdnext/venv"                          
13:25:36-260884 INFO     Version: app=sd.next updated=2025-07-06 hash=d5d857aa  
                         branch=master                                          
                         url=https://github.com/vladmandic/sdnext.git/tree/maste
                         r ui=main                                              
13:25:36-920892 INFO     Version: app=sd.next latest=2025-07-06T00:17:54Z       
                         hash=d5d857aa branch=master                            
13:25:36-931228 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=6.11.0-29-generic python=3.10.18               
                         locale=('en_US', 'UTF-8') docker=False                 
13:25:36-932309 INFO     Args: ['--use-rocm', '--autolaunch']                   
13:25:36-951049 INFO     ROCm: AMD toolkit detected                             
13:25:36-969007 INFO     ROCm: agents=['gfx1201']                               
13:25:36-969564 INFO     ROCm: version=6.4, using agent gfx1201                 
13:25:36-995297 WARNING  Deleted files: ['models/.placeholder',                 
                         'models/Reference/Alpha-VLLM--Lumina-Image-2.0.jpg',   
                         'models/Reference/Alpha-VLLM--Lumina-Next-SFT-diffusers
                         .jpg', 'models/Reference/DeepFloyd--IF-I-M-v1.0.jpg',  
                         'models/Reference/Efficient-Large-Model--Sana_1600M_102
                         4px_diffusers.jpg',                                    
                         'models/Reference/HiDream-ai--HiDream-I1-Fast.jpg',    
                         'models/Reference/IDKiro--sdxs-512-dreamshaper.jpg',   
                         'models/Reference/Kwai-Kolors--Kolors-diffusers.jpg',  
                         'models/Reference/MeissonFlow--Meissonic.jpg',         
                         'models/Reference/OmniGen2--OmniGen2.jpg',             
                         'models/Reference/PixArt-alpha--PixArt-Sigma-XL-2-1024-
                         MS.jpg',                                               
                         'models/Reference/PixArt-alpha--PixArt-XL-2-1024-MS.jpg
                         ',                                                     
                         'models/Reference/PixArt-alpha--PixArt-XL-2-512x512.jpg
                         ',                                                     
                         'models/Reference/PixArt-alpha--pixart_sigma_sdxlvae_T5
                         _diffusers.jpg',                                       
                         'models/Reference/SDXL-Flash_Mini.jpg',                
                         'models/Reference/Shitao--OmniGen-v1.jpg',             
                         'models/Reference/SimianLuo--LCM_Dreamshaper_v7.jpg',  
                         'models/Reference/THUDM--CogView3-Plus-3B.jpg',        
                         'models/Reference/THUDM--CogView4-6B.jpg',             
                         'models/Reference/TempestV0.1-Artistic.jpg',           
                         'models/Reference/Tencent-Hunyuan--HunyuanDiT-v1.2-Diff
                         users.jpg',                                            
                         'models/Reference/XCLiu--instaflow_0_9B_from_sd_1_5.jpg
                         ', 'models/Reference/amused--amused-256.jpg',          
                         'models/Reference/amused--amused-512.jpg',             
                         'models/Reference/black-forest-labs--FLUX.1-Kontext-dev
                         .jpg',                                                 
                         'models/Reference/black-forest-labs--FLUX.1-dev.jpg',  
                         'models/Reference/black-forest-labs--FLUX.1-schnell.jpg
                         ',                                                     
                         'models/Reference/damo-vilab--text-to-video-ms-1.7b.jpg
                         ', 'models/Reference/dreamshaperXL_v21TurboDPMSDE.jpg',
                         'models/Reference/dreamshaper_8.jpg',                  
                         'models/Reference/etri-vilab--koala-700m-llava-cap.jpg'
                         , 'models/Reference/fal--AuraFlow-v0.3.jpg',           
                         'models/Reference/juggernautXL_v9Rdphoto2Lightning.jpg'
                         ,                                                      
                         'models/Reference/juggernautXL_v9Rundiffusionphoto2.jpg
                         ', 'models/Reference/juggernaut_reborn.jpg',           
                         'models/Reference/kandinsky-community--kandinsky-2-1.jp
                         g',                                                    
                         'models/Reference/kandinsky-community--kandinsky-2-2-de
                         coder.jpg',                                            
                         'models/Reference/kandinsky-community--kandinsky-3.jpg'
                         , 'models/Reference/latent-consistency--lcm-sdxl.jpg', 
                         'models/Reference/lodestones--Chroma.jpg',             
                         'models/Reference/nvidia--Cosmos-Predict2-2B-Text2Image
                         .jpg', 'models/Reference/ostris--Flex.1-alpha.jpg',    
                         'models/Reference/ostris--Flex.2-preview.jpg',         
                         'models/Reference/playgroundai--playground-v1.jpg',    
                         'models/Reference/playgroundai--playground-v2-1024px-ae
                         sthetic.jpg',                                          
                         'models/Reference/playgroundai--playground-v2-256px-bas
                         e.jpg',                                                
                         'models/Reference/playgroundai--playground-v2-512px-bas
                         e.jpg',                                                
                         'models/Reference/playgroundai--playground-v2.5-1024px-
                         aesthetic.jpg',                                        
                         'models/Reference/salesforce--blipdiffusion.jpg',      
                         'models/Reference/sd_xl_base_1.0.jpg',                 
                         'models/Reference/sdxl_turbo.jpg',                     
                         'models/Reference/segmind--SSD-1B.jpg',                
                         'models/Reference/segmind--SegMoE-2x1-v0.jpg',         
                         'models/Reference/segmind--SegMoE-4x2-v0.jpg',         
                         'models/Reference/segmind--SegMoE-SD-4x2-v0.jpg',      
                         'models/Reference/segmind--Segmind-Vega.jpg',          
                         'models/Reference/segmind--tiny-sd.jpg',               
                         'models/Reference/shuttleai--shuttle-3-diffusion.jpg', 
                         'models/Reference/stabilityai--stable-cascade.jpg',    
                         'models/Reference/stabilityai--stable-diffusion-2-1-bas
                         e.jpg',                                                
                         'models/Reference/stabilityai--stable-diffusion-2-1.jpg
                         ',                                                     
                         'models/Reference/stabilityai--stable-diffusion-3.jpg',
                         'models/Reference/stabilityai--stable-diffusion-3_5.jpg
                         ',                                                     
                         'models/Reference/stabilityai--stable-video-diffusion-i
                         mg2vid-xt.jpg',                                        
                         'models/Reference/stabilityai--stable-video-diffusion-i
                         mg2vid.jpg',                                           
                         'models/Reference/thu-ml--unidiffuser-v1.jpg',         
                         'models/Reference/v1-5-pruned-fp16-emaonly.jpg',       
                         'models/Reference/warp-ai--wuerstchen.jpg',            
                         'models/VAE-approx/model.pt',                          
                         'models/karlo/ViT-L-14_stats.th', 'embeddings',        
                         'models']                                              
13:25:36-997409 WARNING  Modified files: ['models/VAE-approx/model.pt',         
                         'models/karlo/ViT-L-14_stats.th']                      
13:25:37-007630 INFO     Install: verifying requirements                        
13:25:37-019387 INFO     Extensions: disabled=[]                                
13:25:37-019819 INFO     Extensions: path="extensions-builtin"                  
                         enabled=['sd-extension-system-info', 'Lora',           
                         'sd-webui-agent-scheduler', 'sdnext-modernui',         
                         'sd-extension-chainner',                               
                         'stable-diffusion-webui-rembg']                        
13:25:37-020430 INFO     Extensions: path="extensions" enabled=[]               
13:25:37-020974 INFO     Startup: quick launch                                  
13:25:37-021362 INFO     Extensions: disabled=[]                                
13:25:37-021687 INFO     Extensions: path="extensions-builtin"                  
                         enabled=['sd-extension-system-info', 'Lora',           
                         'sd-webui-agent-scheduler', 'sdnext-modernui',         
                         'sd-extension-chainner',                               
                         'stable-diffusion-webui-rembg']                        
13:25:37-022218 INFO     Extensions: path="extensions" enabled=[]               
13:25:37-023119 INFO     Installer time: total=0.93 latest=0.69                 
13:25:37-023602 INFO     Command line args: ['--use-rocm', '--autolaunch']      
                         autolaunch=True use_rocm=True args=[]                  
13:25:39-071659 INFO     Torch: torch==2.9.0                                    
                         torchvision==0.24.0.dev20250705+rocm6.4                
13:25:39-073181 INFO     Packages: diffusers==0.35.0.dev0 transformers==4.53.0  
                         accelerate==1.8.1 gradio==3.43.2 pydantic==1.10.21     
13:25:43-331024 INFO     Device detect: memory=15.9 default=balanced            
13:25:43-333150 INFO     Engine: backend=Backend.DIFFUSERS compute=rocm         
                         device=cuda attention="Scaled-Dot-Product" mode=no_grad
```

### Relevant log output

```shell
(venv) nick@Z890-EAGLE-WIFI7:~/sdnext$ bash webui.sh
Activate python venv: /home/nick/sdnext/venv
Launch: venv/bin/python3
13:25:36-231899 INFO     Starting SD.Next                                       
13:25:36-233318 INFO     Logger: file="/home/nick/sdnext/sdnext.log" level=INFO 
                         host="Z890-EAGLE-WIFI7" size=2958248 mode=append       
13:25:36-233810 INFO     Python: version=3.10.18 platform=Linux                 
                         bin="/home/nick/sdnext/venv/bin/python3"               
                         venv="/home/nick/sdnext/venv"                          
13:25:36-260884 INFO     Version: app=sd.next updated=2025-07-06 hash=d5d857aa  
                         branch=master                                          
                         url=https://github.com/vladmandic/sdnext.git/tree/maste
                         r ui=main                                              
13:25:36-920892 INFO     Version: app=sd.next latest=2025-07-06T00:17:54Z       
                         hash=d5d857aa branch=master                            
13:25:36-931228 INFO     Platform: arch=x86_64 cpu=x86_64 system=Linux          
                         release=6.11.0-29-generic python=3.10.18               
                         locale=('en_US', 'UTF-8') docker=False                 
13:25:36-932309 INFO     Args: ['--use-rocm', '--autolaunch']                   
13:25:36-951049 INFO     ROCm: AMD toolkit detected                             
13:25:36-969007 INFO     ROCm: agents=['gfx1201']                               
13:25:36-969564 INFO     ROCm: version=6.4, using agent gfx1201                 
13:25:36-995297 WARNING  Deleted files: ['models/.placeholder',                 
                         'models/Reference/Alpha-VLLM--Lumina-Image-2.0.jpg',   
                         'models/Reference/Alpha-VLLM--Lumina-Next-SFT-diffusers
                         .jpg', 'models/Reference/DeepFloyd--IF-I-M-v1.0.jpg',  
                         'models/Reference/Efficient-Large-Model--Sana_1600M_102
                         4px_diffusers.jpg',                                    
                         'models/Reference/HiDream-ai--HiDream-I1-Fast.jpg',    
                         'models/Reference/IDKiro--sdxs-512-dreamshaper.jpg',   
                         'models/Reference/Kwai-Kolors--Kolors-diffusers.jpg',  
                         'models/Reference/MeissonFlow--Meissonic.jpg',         
                         'models/Reference/OmniGen2--OmniGen2.jpg',             
                         'models/Reference/PixArt-alpha--PixArt-Sigma-XL-2-1024-
                         MS.jpg',                                               
                         'models/Reference/PixArt-alpha--PixArt-XL-2-1024-MS.jpg
                         ',                                                     
                         'models/Reference/PixArt-alpha--PixArt-XL-2-512x512.jpg
                         ',                                                     
                         'models/Reference/PixArt-alpha--pixart_sigma_sdxlvae_T5
                         _diffusers.jpg',                                       
                         'models/Reference/SDXL-Flash_Mini.jpg',                
                         'models/Reference/Shitao--OmniGen-v1.jpg',             
                         'models/Reference/SimianLuo--LCM_Dreamshaper_v7.jpg',  
                         'models/Reference/THUDM--CogView3-Plus-3B.jpg',        
                         'models/Reference/THUDM--CogView4-6B.jpg',             
                         'models/Reference/TempestV0.1-Artistic.jpg',           
                         'models/Reference/Tencent-Hunyuan--HunyuanDiT-v1.2-Diff
                         users.jpg',                                            
                         'models/Reference/XCLiu--instaflow_0_9B_from_sd_1_5.jpg
                         ', 'models/Reference/amused--amused-256.jpg',          
                         'models/Reference/amused--amused-512.jpg',             
                         'models/Reference/black-forest-labs--FLUX.1-Kontext-dev
                         .jpg',                                                 
                         'models/Reference/black-forest-labs--FLUX.1-dev.jpg',  
                         'models/Reference/black-forest-labs--FLUX.1-schnell.jpg
                         ',                                                     
                         'models/Reference/damo-vilab--text-to-video-ms-1.7b.jpg
                         ', 'models/Reference/dreamshaperXL_v21TurboDPMSDE.jpg',
                         'models/Reference/dreamshaper_8.jpg',                  
                         'models/Reference/etri-vilab--koala-700m-llava-cap.jpg'
                         , 'models/Reference/fal--AuraFlow-v0.3.jpg',           
                         'models/Reference/juggernautXL_v9Rdphoto2Lightning.jpg'
                         ,                                                      
                         'models/Reference/juggernautXL_v9Rundiffusionphoto2.jpg
                         ', 'models/Reference/juggernaut_reborn.jpg',           
                         'models/Reference/kandinsky-community--kandinsky-2-1.jp
                         g',                                                    
                         'models/Reference/kandinsky-community--kandinsky-2-2-de
                         coder.jpg',                                            
                         'models/Reference/kandinsky-community--kandinsky-3.jpg'
                         , 'models/Reference/latent-consistency--lcm-sdxl.jpg', 
                         'models/Reference/lodestones--Chroma.jpg',             
                         'models/Reference/nvidia--Cosmos-Predict2-2B-Text2Image
                         .jpg', 'models/Reference/ostris--Flex.1-alpha.jpg',    
                         'models/Reference/ostris--Flex.2-preview.jpg',         
                         'models/Reference/playgroundai--playground-v1.jpg',    
                         'models/Reference/playgroundai--playground-v2-1024px-ae
                         sthetic.jpg',                                          
                         'models/Reference/playgroundai--playground-v2-256px-bas
                         e.jpg',                                                
                         'models/Reference/playgroundai--playground-v2-512px-bas
                         e.jpg',                                                
                         'models/Reference/playgroundai--playground-v2.5-1024px-
                         aesthetic.jpg',                                        
                         'models/Reference/salesforce--blipdiffusion.jpg',      
                         'models/Reference/sd_xl_base_1.0.jpg',                 
                         'models/Reference/sdxl_turbo.jpg',                     
                         'models/Reference/segmind--SSD-1B.jpg',                
                         'models/Reference/segmind--SegMoE-2x1-v0.jpg',         
                         'models/Reference/segmind--SegMoE-4x2-v0.jpg',         
                         'models/Reference/segmind--SegMoE-SD-4x2-v0.jpg',      
                         'models/Reference/segmind--Segmind-Vega.jpg',          
                         'models/Reference/segmind--tiny-sd.jpg',               
                         'models/Reference/shuttleai--shuttle-3-diffusion.jpg', 
                         'models/Reference/stabilityai--stable-cascade.jpg',    
                         'models/Reference/stabilityai--stable-diffusion-2-1-bas
                         e.jpg',                                                
                         'models/Reference/stabilityai--stable-diffusion-2-1.jpg
                         ',                                                     
                         'models/Reference/stabilityai--stable-diffusion-3.jpg',
                         'models/Reference/stabilityai--stable-diffusion-3_5.jpg
                         ',                                                     
                         'models/Reference/stabilityai--stable-video-diffusion-i
                         mg2vid-xt.jpg',                                        
                         'models/Reference/stabilityai--stable-video-diffusion-i
                         mg2vid.jpg',                                           
                         'models/Reference/thu-ml--unidiffuser-v1.jpg',         
                         'models/Reference/v1-5-pruned-fp16-emaonly.jpg',       
                         'models/Reference/warp-ai--wuerstchen.jpg',            
                         'models/VAE-approx/model.pt',                          
                         'models/karlo/ViT-L-14_stats.th', 'embeddings',        
                         'models']                                              
13:25:36-997409 WARNING  Modified files: ['models/VAE-approx/model.pt',         
                         'models/karlo/ViT-L-14_stats.th']                      
13:25:37-007630 INFO     Install: verifying requirements                        
13:25:37-019387 INFO     Extensions: disabled=[]                                
13:25:37-019819 INFO     Extensions: path="extensions-builtin"                  
                         enabled=['sd-extension-system-info', 'Lora',           
                         'sd-webui-agent-scheduler', 'sdnext-modernui',         
                         'sd-extension-chainner',                               
                         'stable-diffusion-webui-rembg']                        
13:25:37-020430 INFO     Extensions: path="extensions" enabled=[]               
13:25:37-020974 INFO     Startup: quick launch                                  
13:25:37-021362 INFO     Extensions: disabled=[]                                
13:25:37-021687 INFO     Extensions: path="extensions-builtin"                  
                         enabled=['sd-extension-system-info', 'Lora',           
                         'sd-webui-agent-scheduler', 'sdnext-modernui',         
                         'sd-extension-chainner',                               
                         'stable-diffusion-webui-rembg']                        
13:25:37-022218 INFO     Extensions: path="extensions" enabled=[]               
13:25:37-023119 INFO     Installer time: total=0.93 latest=0.69                 
13:25:37-023602 INFO     Command line args: ['--use-rocm', '--autolaunch']      
                         autolaunch=True use_rocm=True args=[]                  
13:25:39-071659 INFO     Torch: torch==2.9.0                                    
                         torchvision==0.24.0.dev20250705+rocm6.4                
13:25:39-073181 INFO     Packages: diffusers==0.35.0.dev0 transformers==4.53.0  
                         accelerate==1.8.1 gradio==3.43.2 pydantic==1.10.21     
13:25:43-331024 INFO     Device detect: memory=15.9 default=balanced            
13:25:43-333150 INFO     Engine: backend=Backend.DIFFUSERS compute=rocm         
                         device=cuda attention="Scaled-Dot-Product" mode=no_grad
13:26:56-621985 ERROR    Install: pip: install --upgrade                        
                         git+https://github.com/Disty0/flash-attention@navi_rota
                         ry_fix                                                 
13:26:56-635368 ERROR    Torch attention: type="ck flash attention" No module   
                         named 'flash_attn'                                     
13:26:56-790584 INFO     Torch parameters: backend=rocm device=cuda config=FP16 
                         dtype=torch.float16 context=no_grad nohalf=False       
                         nohalfvae=False upcast=False deterministic=False       
                         tunable=[False, True] fp16=pass bf16=pass              
                         optimization="Scaled-Dot-Product"                      
13:26:56-791715 INFO     Device: device=AMD Radeon RX 9070 n=1                  
                         hip=6.4.43483-a187df25c     


Full compilation log:  https://pastebin.com/MqZ2KTth
```

### Backend

Diffusers

### Compute

AMD ROCm

### UI

ModernUI

### Branch

Master

### Model

StableDiffusion XL

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by Disty0** [comment]
It compiles fine with Torch 2.8 + ROCm 6.4.1 with RX 7900 XTX.
Updated the wiki page to reflect that ck flash atten is pretty much RDNA 3 only.

Also i wasn't aware that issues were disabled in mt flash atten fork, enabled them now.

**Comment by vladmandic** [comment]
should this issue be closed or?

**Comment by Disty0** [comment]
Yeah, someone has to write CK flash atten for RX 9000 for CK to work. Meanwhile the default AOTriton flash atten from PyTorch should be good enough.
