### ISSUE TITLE
[Issue]: Can't start webui, dependency change?

### ISSUE THREAD

**Issue by AlonzoTG** [vladmandic/sdnext#3800]
### Issue Description

Rebooted my system, and tried to git pull then launch. No other changes: 

C:\Users\atg\Documents\GitHub\automatic>webui.bat
Using VENV: C:\Users\atg\Documents\GitHub\automatic\venv
Traceback (most recent call last):
  File "C:\Users\atg\Documents\GitHub\automatic\launch.py", line 283, in <module>
    main()
  File "C:\Users\atg\Documents\GitHub\automatic\launch.py", line 203, in main
    init_args() # setup argparser and default folders
    ^^^^^^^^^^^
  File "C:\Users\atg\Documents\GitHub\automatic\launch.py", line 36, in init_args
    import modules.cmd_args
  File "C:\Users\atg\Documents\GitHub\automatic\modules\cmd_args.py", line 4, in <module>
    from modules.paths import data_path
  File "C:\Users\atg\Documents\GitHub\automatic\modules\paths.py", line 7, in <module>
    from modules.errors import log
  File "C:\Users\atg\Documents\GitHub\automatic\modules\errors.py", line 7, in <module>
    setup_logging()
  File "C:\Users\atg\Documents\GitHub\automatic\installer.py", line 171, in setup_logging
    install_traceback()
  File "C:\Users\atg\Documents\GitHub\automatic\installer.py", line 89, in install_traceback
    traceback_install(
TypeError: install() got an unexpected keyword argument 'code_width'
Press any key to continue . . .

C:\Users\atg\Documents\GitHub\automatic>

### Version Platform Description

windows 10,  python 3.12.7

### Relevant log output

```shell

```

### Backend

Diffusers

### UI

Standard

### Branch

Master

### Model

StableDiffusion 1.5

### Acknowledgements

- [x] I have read the above and searched for existing issues
- [x] I confirm that this is classified correctly and its not an extension issue

**Comment by vladmandic** [comment]
@Disty0 can you check if there is change in latest `rich`?

**Comment by Disty0** [comment]
It works fine with the latest (13.9.4) but 13.6.0 doesn't have code_width.
@vladmandic  installer can't start if an older version is installed.

**Comment by Disty0** [comment]
I can add a version check like this or just comment out the code_width block, which one do you prefer @vladmandic?

```
rich_version = float(package_version('rich')[:-2])
if rich_version < 13.9:
```

**Comment by vladmandic** [comment]
thanks - let's just remove code_width

**Comment by Disty0** [comment]
Done: https://github.com/vladmandic/sdnext/commit/227c4b5d107775d8250051f1c4634735e8aaee4a

Also did a master refresh since this one is critical enough to require it.

**Comment by vladmandic** [comment]
thanks!

**Comment by Disty0** [comment]
This issue should be fixed if you do another git pull. Feel free to reopen if it still persist.
